[project]
name = "ai-agents-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.1.45",
    "patchright>=1.52.3",
]
